name: Boot DVD CI

on:
  pull_request: {}
  push:
    branches:
    - main
  workflow_dispatch: {}

jobs:
  main:
    name: Build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: boot_dvd

    steps:
    - name: Check out sources
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - name: Set up Git
      run: |
        # Configures the global `git` CLI to be able to access private repos.
        git config --global url.'https://github.com/'.insteadOf 'git@github.com:'
        # Copy the encoded auth token from local config that actions/checkout configured.
        git config --global http.'https://github.com/'.extraHeader "$(git config --local http.'https://github.com/'.extraHeader)"

    - name: Run shellcheck
      run: |
        shellcheck --version
        shellcheck *.sh internal/*.sh

    - name: Split inputs hashes
      run: |
        grep -E '  \./inputs/apt/' sha256sum.inputs.txt > sha256sum.inputs-apt.txt
        grep -E '  \./inputs/(crates/|juicebox-hsm-realm\.tar$)' sha256sum.inputs.txt > sha256sum.inputs-code.txt
        grep -E '  \./inputs/rust-.*\.tar\.xz$' sha256sum.inputs.txt > sha256sum.inputs-rust.txt

    - name: Restore apt cache
      uses: actions/cache/restore@v3
      id: restore-apt-cache
      with:
        path: boot_dvd/inputs/apt
        key: ${{ runner.os }}-${{ hashFiles(
            'boot_dvd/sha256sum.inputs-apt.txt',
            'boot_dvd/get-debs.sh',
            'boot_dvd/internal/make-cache-dir.sh',
          ) }}

    - name: Download apt files
      # This is done unconditionally since it's fast. It doesn't download
      # anything if the files in 'inputs/apt' exist.
      run: ./get-debs.sh

    - name: Check apt files
      run: |
        find ./inputs/apt -type f | \
          LC_ALL=C sort | \
          xargs sha256sum | \
          diff -u sha256sum.inputs-apt.txt -

    - name: Save apt cache
      if: steps.restore-apt-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: boot_dvd/inputs/apt
        key: ${{ steps.restore-apt-cache.outputs.cache-primary-key }}

    - name: Download Rust
      run: ./get-rust.sh

    - name: Check Rust downloads
      run: |
        sha256sum ./inputs/rust-*-linux-*.tar.xz ./inputs/rust-src-*.tar.xz | \
          diff -u sha256sum.inputs-rust.txt -

    - name: Restore code/crates cache
      uses: actions/cache/restore@v3
      id: restore-code-cache
      with:
        path: |
          boot_dvd/inputs/crates/
          boot_dvd/inputs/juicebox-hsm-realm.tar
        key: ${{ runner.os }}-${{ hashFiles(
            'boot_dvd/sha256sum.inputs-code.txt',
            'boot_dvd/sha256sum.inputs-rust.txt',
            'boot_dvd/get-code.sh',
            'boot_dvd/get-crates.sh',
            'boot_dvd/internal/get-crates-inner.sh',
            'boot_dvd/internal/make-cache-dir.sh',
            'boot_dvd/internal/vars.sh',
          ) }}

    - name: Package/download code
      # This is done unconditionally since it's fast. It doesn't download
      # anything if 'inputs/juicebox-hsm-realm.tar' exists.
      run: ./get-code.sh

    - name: Download crates
      if: steps.restore-code-cache.outputs.cache-hit != 'true'
      run: ./get-crates.sh

    - name: Check code/crates inputs
      run: |
        find ./inputs/crates ./inputs/juicebox-hsm-realm.tar -type f | \
          LC_ALL=C sort | \
          xargs sha256sum | \
          diff -u sha256sum.inputs-code.txt -

    - name: Save code/crates cache
      if: steps.restore-code-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v3
      with:
        path: |
          boot_dvd/inputs/crates/
          boot_dvd/inputs/juicebox-hsm-realm.tar
        key: ${{ steps.restore-code-cache.outputs.cache-primary-key }}

    - name: Check all inputs
      run: |
        find ./inputs -type f | \
          LC_ALL=C sort | \
          xargs sha256sum | \
          diff -u sha256sum.inputs.txt -

    - name: Build ISO
      run: ./build.sh
